### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by blanham** [JMarlin/wsbe#2]
It seems like your website is currently down. Would it be possible to add the site's content to the git repo?

**Comment by JMarlin** [comment]
WOW it has been a long time since I last looked at this repo. It would certainly be a great idea to get the site content mirrored over here, and I'm going to leave this issue open for the time being and transfer the content over as I have time.

If anyone else is dying for this and sees this open issue, I would have zero problem if you started doing this yourself and sent me a pull request. But that said, seeing as this is a _super_ dead topic I'll figure that's never going to happen and try to be somewhat proactive myself.

**Comment by jaccarmac** [comment]
I'd be interested in pulling content over, however I can only find the last few installments on the Internet Archive. Only the fifth post and onward are available.

**Comment by blanham** [comment]
@JMarlin?

**Comment by JMarlin** [comment]
Critical system error: I am dead.

I know my blog has been down for about three forevers. I've gotten emails about it, I've got this here, and I've ignored all of them almost entirely out of apathy. And frankly, that blog embarrasses me a little bit. 

But I suppose I should've taken into account how lazy I am and how crap my output would be before I published.

To that end -- and this is ridiculous considering how long it's been down -- I'm going to do something about getting trackze.ro back up in some way today. 

If there's anything I can do to repent for not doing this simple thing for months and months, just lemme know.

**Comment by JMarlin** [comment]
Wow, you guys are really going to love this. I didn't want to deal with it largely because I figured my domain name had expired again and I'd probably have to go through the whole rigamarole of trying to get it back, like last time this happened, or trying to find a new one even remotely as cool.

Yeah, no. My server just got rebooted and I'm too dumb to put the startup for my blogging platform into  my init.

CLOSED.
