### ISSUE TITLE
trackze.ro is down

### ISSUE THREAD

**Issue by CodeVisio** [JMarlin/wsbe#3]
Hi,
as in the subject.
Is it a temporary issue or did you close it?

Thanks

**Comment by JMarlin** [comment]
This has been a constant headache for me. That server was absolute garbage.
I just pulled the content off the server, when I find some time I'll get it rehosted in some way that isn't awful.

**Comment by JetStarBlues** [comment]
Would you consider Github pages for hosting?

**Comment by valentinbreiz** [comment]
@CodeVisio when you're interested in osdev, Wayback Machine is your friend (https://web.archive.org/web/20200428203825/http://www.trackze.ro/)

Also many thanks for your work @JMarlin

**Comment by JMarlin** [comment]
Finally got this into a more permanent place. Don't know why github pages never really occurred to me, but great suggestion JetStarBlues

And thanks for the thanks, valentinbriez, but I've been pretty slobby with maintaining this thing and it's more or less the only thing I'm at all known for so I don't know that I deserve the praise.

**Comment by JetStarBlues** [comment]
@JMarlin Hi, that's good to hear! I hope it proves to be more stable.

I took a look at the new site. It looks like the import left a few loose ends:

- pictures are missing _(high priority)_
  - Using inspector tools, can see that this due to the `<img src>` referencing `web.archive.org` urls
- outgoing links are prefixed with `web.archive.org` _(low priority)_
- there's no syntax highlighting _(low priority)_

For example, compare this [old page][0] with the [current][1].

Thank you for the great resource! I learned a lot from it!

---
#### Edit
Just looked at the current issues, and I see you have already opened issues for all three.


[0]: https://web.archive.org/web/20180715114612/http://trackze.ro/wsbe-complicated-rectangles/
[1]: https://jmarlin.github.io/wsbe/2016/08/17/1-complicated-rectangles.html
